CJ/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


# Discover admin
admin.autodiscover()

# Define handlers for errors
handler404 = 'codeit.blogviews.my_custom_404_view'
handler500 = 'codeit.blogviews.my_custom_error_view'
handler403 = 'codeit.blogviews.my_custom_permission_denied_view'

# Url mapping
urlpatterns = patterns('',
    url(r'^$', 'codeit.views.index', name='index'),
    url(r'^home/$', 'codeit.views.home', name='home'),
    url(r'^contact/$', 'codeit.views.contact', name='contact'),
    url(r'^about/$', 'codeit.views.about', name='about'),
    url(r'^logout/$', 'codeit.views.logout', name='logout'),
    url(r'^ranking/$', 'codeit.views.ranking', name='ranking'),
    url(r'^feedback/$', 'codeit.blogviews.feedback', name='feedback'),
    url(r'^demo/$', 'codeit.views.demo', name='demo'),
    url(r'^problem/(?P<problem_id>\d+)/$', 'codeit.views.problem', name='problem'),
    url(r'^solution/(?P<problem_id>\d+)/$', 'codeit.views.solution', name='solution'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/$', 'codeit.blogviews.blogindex', name='blogindex'),
    url(r'^blog/(?P<post_id>\d+)/$', 'codeit.blogviews.blogdetail', name='blogdetail'),
    url(r'^questions/(?P<ptype>\d)/$', 'codeit.views.questions', name='questions'),
    url(r'^submission/(?P<receipt_no>\d+)/$', 'codeit.views.submission', name='submission'),
)
urlpatterns += staticfiles_urlpatterns()

codeit/models.py
from django.db import models
from django.utils import timezone
import datetime


class Post(models.Model):
    """
    Model represents each post individually for blog
    @post_name => post NAME
    @post_text => post text
    @pub_date  => date on which post is published
    """
    post_name = models.CharField(max_length=200)
    post_text = models.TextField()
    pub_date = models.DateTimeField("date published")

    def __unicode__(self):
        return self.post_name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = "pub_date"
    was_published_recently.boolean = True
    was_published_recently.short_description = "Published recently?"


def problem_function(instance, filename):
    return "/".join(["problem", filename])


class Problem(models.Model):
    """
    """
    name = models.CharField(max_length=150)
    statement = models.TextField()
    year = models.IntegerField()
    points = models.IntegerField()
    sample_input = models.TextField()
    sample_output = models.TextField()
    standard_input = models.FileField(upload_to=problem_function)
    standard_output = models.FileField(upload_to=problem_function)

    def __unicode__(self):
        return self.name


class User(models.Model):
    """
    """
    receipt_no = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    total_points = models.IntegerField()
    year = models.CharField(max_length=5)
    isactive = models.BooleanField(default=False)
    solved = models.ManyToManyField(Problem)

    def user_active(self):
        return self.isactive
    user_active.admin_order_field = "isactive"
    user_active.boolean = True
    user_active.short_description = "Active now ?"

    def fullname(self):
        return str(self.first_name) + " " + str(self.last_name)

    def __unicode__(self):
        return str(self.first_name) + " " + str(self.last_name)


def my_function(instance, filename):
    filename = filename.split(".")
    path = "/".join(["documents", str(instance.user.receipt_no), instance.problem.name + "-"
        + str(filename[0]) + "." + instance.language.lower()])
    path = path.replace(" ", "")
    return path


class Solution(models.Model):
    """
    """
    problem = models.ForeignKey(Problem)
    user = models.ForeignKey(User)
    text = models.FileField(upload_to=my_function)
    language = models.CharField(max_length=20)
    points_obtained = models.IntegerField()
    sub_date = models.DateTimeField()

    def __unicode__(self):
        return str(self.problem) + " " + str(self.user)


class Feedback(models.Model):
    """
    """
    name = models.ForeignKey(User)
    fdproblems = models.TextField()
    fdsoft = models.TextField()
    fdsugg = models.TextField()

codeit/forms.py
from django import forms


class UserForm(forms.Form):
    receipt_no = forms.IntegerField(label="Receipt No", widget=forms.TextInput(attrs={
      'placeholder': 'Receipt No'
      }))
    first_name = forms.CharField(label="First Name",  widget=forms.TextInput(attrs={
      'placeholder': 'First Name'
      }))
    last_name = forms.CharField(label="Last Name", widget=forms.TextInput(attrs={
      'placeholder': 'Last Name'
      }))
    CHOICES = (
      ('fe', 'F.E.'),
      ('se', 'S.E.'),
      ('te', 'T.E'),
      ('be', 'B.E'),
      ('mca', 'M.C.A'),
      )
    year = forms.ChoiceField(choices=CHOICES)


class FileUploadForm(forms.Form):
    code = forms.FileField(
        label="Select code file to Upload",
        )
    CHOICES = (
      ("c", "C"),
      ("cpp", "C++"),
      ("java", "Java"),
      ("py", "Python"),
      )
    picked = forms.ChoiceField(choices=CHOICES, label="Select your language")


class FeedbackForm(forms.Form):
    fdproblem = forms.CharField(label="About Problems", widget=forms.Textarea)
    fdsoft = forms.CharField(label="About Software", widget=forms.Textarea)
    fdsugg = forms.CharField(label="Other suggestions", widget=forms.Textarea)

codeit/views.py
from django.shortcuts import render_to_response, redirect
from django.views.decorators.cache import cache_control
from django.core.files.storage import default_storage
from codeit.forms import UserForm, FileUploadForm
from django.template import RequestContext
from django.conf import settings
from codeit.models import *
from codeit.execute import *
from django.utils import timezone
import os
from django.core import serializers
from django.http import HttpResponse


def index(request):
    """
    This function validates user login ,
    manages whole user information.
    """
    #Check if user already started session
    if "receipt_no" in request.session:
        return redirect("/home/")

    # If user posting data
    if request.method == "POST":
        form = UserForm(request.POST)
        #Check form field is valid or not
        if form.is_valid():
            #Extract data from form
            receipt_no = form.cleaned_data["receipt_no"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]

            try:
                year = request.POST["year"]
            except:
                return render_to_response("error/error.html",
                    {"message": message,
                    })
            first_name = first_name.capitalize()
            last_name = last_name.capitalize()

            #Get all objects with that receipt no.
            temp = User.objects.filter(receipt_no=int(receipt_no))
            # Receipt no not found.
            if temp.count() == 0:
                message = """
                    You dont have right receipt no.
                    Contact server adminstrator.
                    Back To Login
                    """
                return render_to_response("error/error.html",
                    {"message": message,
                    },
                    context_instance=RequestContext(request),
                    )
            # Receipt no duplcated.
            elif temp.count() > 1:
                # This is never going to happen :-( Still
                message = """
                     Your receipt no is duplicated.<br>
                    Contact server adminstrator.
                    """
                return render_to_response("error/error.html",
                    {"message": message,
                    },
                    context_instance=RequestContext(request),
                    )
            #Set first_name, last_name for user
            u = temp[0]
            if u.isactive == False:
                u.first_name = first_name
                u.last_name = last_name
                u.year = year
                u.isactive = True
                u.save()
                request.session["receipt_no"] = u.receipt_no
                path = "/".join([settings.MEDIA_ROOT, "documents", str(u.receipt_no) + "/"])
                if not os.path.exists(path):
                    print "Document path doesnt exit"
                    try:
                        os.makedirs(path)
                    except:
                        print "Not able to create document path"
                return redirect("/home/")
            else:
                message = "User with receipt no Already logged in.\nContact server adminstrator"
                return render_to_response("error/error.html",
                    {"message": message,
                    },
                    context_instance=RequestContext(request)
                    )
                return redirect("/")
        else:
            return render_to_response("codeit/index.html",
             {"userform": form},
             context_instance=RequestContext(request))
    else:
        userform = UserForm()
        return render_to_response("codeit/index.html",
            {"userform": userform},
            context_instance=RequestContext(request)
            )


@cache_control(no_cache=True,
    must_revalidate=True,
    no_store=True,
    )
@login_required
def home(request):
    """
    """
    user = getuser(request.session["receipt_no"])
    username = user.fullname()
    if user.year == "fe" or user.year == "se":
        problems = Problem.objects.filter(year__lt=4).order_by("year")
    else:
        problems = Problem.objects.filter(year__gt=3).order_by("year")
    return render_to_response("codeit/home.html",
        {"username": username,
        "problems": problems},
        context_instance=RequestContext(request))


def questions(request, ptype):
    """
    Chaged url in urls.py for passing type.
    We pass type here and get Problems for that type
    Now just testing for 1,2,3.
    Eg. url will be http://127.0.0.1:8000/questions/1/"
    Will return json objets
    """
    content_type = "application/json"
    format = "json"
    user = getuser(request.session["receipt_no"])
    if user.year == "fe" or user.year == "se":
        pass
    else:
        if ptype == "1":
            ptype = "4"
        elif ptype == "2":
            ptype = "5"
        elif ptype == "3":
            ptype = "6"

    if ptype == "1":
        problems = Problem.objects.filter(year__exact=1)
    elif ptype == "2":
        problems = Problem.objects.filter(year__exact=2)
    elif ptype == "3":
        problems = Problem.objects.filter(year__exact=3)
    elif ptype == "4":
        problems = Problem.objects.filter(year__exact=4)
    elif ptype == "5":
        problems = Problem.objects.filter(year__exact=5)
    elif ptype == "6":
        problems = Problem.objects.filter(year__exact=6)
    else:
        return -1

    # Return json data
    data = serializers.serialize(format, problems)
    return HttpResponse(data, mimetype=content_type)


@login_required
def logout(request):
    """
    """
    # Check if request contains session var "username"
    user = getuser(request.session["receipt_no"])
    user.isactive = False
    user.save()
    del request.session["receipt_no"]
    return redirect("/")


@cache_control(no_cache=True,
    must_revalidate=True,
    no_store=True,
)
@login_required
def ranking(request):
    """
    Decide ranking of users from points
    """
    username = getuser(request.session["receipt_no"]).fullname()
    userlist = User.objects.exclude(first_name="-").order_by("-total_points")
    return render_to_response("codeit/ranking.html",
        {"userlist": userlist,
        "username": username,
        },
        context_instance=RequestContext(request)
        )


@login_required
def problem(request, problem_id):
    username = getuser(request.session["receipt_no"]).fullname()
    try:
        problem = Problem.objects.get(pk=problem_id)
    except KeyError:
        message = "Problem not found with given problem_id"
        return render_to_response("error/error.html",
            {"message": message,
            })
    return render_to_response("codeit/problem.html",
        {"problem": problem,
        "fileuploadform": FileUploadForm(),
        "username": username,
        },
        context_instance=RequestContext(request)
        )


@login_required
def contact(request):
    if "receipt_no" in request.session:
        username = getuser(request.session["receipt_no"]).fullname()
        return render_to_response("codeit/contact.html",
            {"username": username,
            },
            context_instance=RequestContext(request)
            )
    return render_to_response("codeit/contact.html",
        {},
        context_instance=RequestContext(request)
        )


@login_required
def about(request):
    if "receipt_no" in request.session:
        username = getuser(request.session["receipt_no"]).fullname()
        return render_to_response("codeit/about.html",
            {"username": username,
            },
            context_instance=RequestContext(request)
            )
    return render_to_response("codeit/about.html",
        {},
        context_instance=RequestContext(request)
        )


def demo(request):
    return render_to_response("codeit/demo.html",
        {},
        context_instance=RequestContext(request),
        )


@login_required
def submission(request, receipt_no):
    username = getuser(request.session["receipt_no"]).fullname()
    solver = getuser(receipt_no).fullname()
    solutions = Solution.objects.filter(user__receipt_no__exact=receipt_no)
    return render_to_response('codeit/submission.html',
        {"solutions": solutions,
        "username": username,
        "solver": solver,
        },
        context_instance=RequestContext(request)
        )


@login_required
def solution(request, problem_id):
    """
    Validates user last submission
    This part works fine now .
    """
    if 'lastsubtime' in request.session:
        diff = timezone.now() - request.session['lastsubtime']
        # Time For execution is temp. 30 should be changed to 120 sec.
        limit = 30
        if diff.seconds < limit:
            message = """
            You have submitted solution recently.
            Submit solution again after ..."""
            diff = str(limit - diff.seconds) + " seconds"
            return render_to_response("error/error.html",
                {'message': message,
                'diff': diff,
                },
                context_instance=RequestContext(request)
                )
        else:
            request.session['lastsubtime'] = timezone.now()
    else:
        request.session['lastsubtime'] = timezone.now()

    """
    Validate user submitting solution
    """
    user = getuser(request.session["receipt_no"])
    if user:
        username = user.fullname()
    else:
        message = """
        You are using wrong receipt_no
        Contact server adminstrator
        """
        return render_to_response('error/error',
            {'message': message,
            },
            context_instance=RequestContext(request)
            )

    """
    Validate user if already submitted solution or not
    """
    try:

templates/codeit/about.html
{% extends "base.html" %}
{% block name %}About {% endblock %}

{% block content %}
<h2>CodeIT </h2>
<hr>
<table width="85%">
    <tr>
        <td>Version 1.0 beta</td>
        <td align="right"><strong><a href="/feedback/">Feedback</a></strong></td>
    </tr>
</table>

<p class="lead">

    CodeIT is an event hosted by our group to inhance and<br>
    encourage programming skills for every student through<br>
    programming problems.<br>
    <br>

    <strong>We support platform which<br>
    Decides ambition..<br>
    Encourages innovation...<br>
    Evaluates perception...!!<br></strong>
    <br>
    <a href="/contact/">Know More About Us.</a>
</p>
{% endblock %}

templates/codeit/blogdetail.html
{% extends "base.html" %}

{% block name %}Archieve{% endblock %}

{% block content %}
<h2>{{ post.post_name }}</h2>

<hr>
<p style="margin-left: 10px;">
  <i>{{post.pub_date}}</i>
</p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% autoescape off %}
<p style="margin: 40px; color: #000;">
  {{ post.post_text|linebreaks}}
</p>
{% endautoescape %}

{% endblock %}

templates/codeit/blogindex.html
{% extends "base.html" %}

{% block name %} Tips {% endblock %}

{% block content %}
<h2>Instructions</h2>

 <hr>

{% if latest_post_list %}
<dl>
  {% for post in latest_post_list %}
  <dt><p class="lead"><a href="{{ post.id}}/">&nbsp;&nbsp;{{ post.post_name }}</a></p></dt>
  <hr>
  {% endfor %}
</dl>
{% else %}
<p> No posts are available </p>
{% endif %}
{% endblock %}

templates/codeit/contact.html
{% extends "base.html" %}
{% block name %}Contact{% endblock %}

{% block layout %}
<style type="text/css">
  .table{
  max-width: 85%;
  margin-left: 25px;
  background-color: transparent;
  border-collapse: collapse;
  border-spacing: 0;
  }
</style>
{% endblock %}

{% block content %}

<h2> Contacts</h2>
<hr>
<table class="table table-hover">
  <tr>
    <td>Sanket Sudake</td>
    <td><a href="mailto:sanketsudake@gmail.com">sanketsudake@gmail.com</a></td>
  </tr>

  <tr>
    <td>Nikhil Pachpande</td>
    <td><a href="mailto:pachpandenikhil@gmail.com">pachpandenikhil@gmail.com</a></td>
  </tr>

  <tr>
    <td>Prathamesh Sonpatki</td>
    <td></td>
  </tr>

  <tr>
    <td>Sagar Rakshe</td>
    <td><a href="mailto:srrakshe419@gmail.com">srrashe419@gmail.com</a></td>
  </tr>

  <tr>
    <td>Chandan Kawale</td>
    <td></td>
  </tr>

  <tr>
    <td>Vinay Hiwarkar</td>
    <td></td>
  </tr>

  <tr>
    <td>Prasanna Mahajan</td>
    <td></td>
  </tr>

  <tr>
    <td>Prasad Lingawar</td>
    <td></td>
  </tr>

  <tr>
    <td>Savitru U.</td>
    <td></td>
  </tr>

  <tr>
    <td>Shreyash Nangunrwar</td>
    <td></td>
  </tr>

</table>


{% endblock %}

templates/codeit/demo.html
{% extends "base.html" %}
{% block name %}Demo{% endblock %}
{% block layout %}

<style type="text/css">
label{
    color: #ffffff;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
    background-color: #7B68EE;
    padding: 4px;
}
.board{
    background-color:#FAFAD2;
    border:1px solid gray;
    border-radius: 5px;
    height: 100px;
    width:300px;
    padding:10px;
    margin-left:20px;
    color:#8B4513;
}
</style>
{% endblock %}

{% block content %}
<h1> Demo</h1>
<hr>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/demo.js"></script>
<table>
  <tr>
    <td colspan=20>
      <div>
       <table>
         <tr>
           <td>
             <label id="nameLabel" style="display : none;">Problem Name</label>
         </td>
         <td>
	      <div id="nameDiv" style="display : none;" align="center">
		<p align="left" id="name_paragraph" class="board">This is the problem name.<br>It summarizes the problem in two or three words</p>
	    	<button class="btn btn-medium btn-success" onclick="showStatement()">
	    	  Got It <i class="icon-thumbs-up icon-white"></i>
	    	</button>
	      </div>
	    </td>
	  </tr>
	</table>
      </div>
      <br>
      <br>
    </td>
  </tr>
  <tr>
    <td colspan=20>
      <br>
      <br>
      <div>
	<table>
	  <tr>
	    <td>
	      <label id="statementLabel" style="display : none;">Problem Statement</label>
	    </td>
	    <td>
	      <br>
	      <br>
	      <div id="statementDiv" style="display : none;" align="center">
		<p align="left" class="board">This is the problem statement.<br>It provides detailed description of the problem</p>
	    	<button class="btn btn-medium btn-success" onclick="showSampleIp()">
	    	  Got It <i class="icon-thumbs-up icon-white"></i>
	    	</button>
	      </div>
	    </td>
	  </tr>
	</table>
      </div>
      <br>
      <br>
    </td>
  </tr>

  <tr>
    <td colspan=20>
      <br>
      <br>
      <div>
	<table>
	  <tr>
	    <td>
	      <label id="sampleIpLabel" style="display : none;">Sample Input</label>
	    </td>
	    <td>
	      <br>
	      <br>
	      <div id="sampleIpDiv" style="display : none;" align="center">
		<p align="left" class="board">You can check the correctness of your program by using these sample inputs<br><u>NOTE:</u>Your program should also work for other acceptable inputs</p>
	    	<button class="btn btn-medium btn-success" onclick="showSampleOp()">
	    	  Got It <i class="icon-thumbs-up icon-white"></i>
	    	</button>
	      </div>
	    </td>
	  </tr>
	</table>
      </div>
      <br>
      <br>
    </td>
  </tr>

  <tr>
    <td colspan=20>
      <br>
      <br>
      <div>
	<table>
	  <tr>
	    <td>
	      <label id="sampleOpLabel" style="display : none;">Sample Output</label>
	    </td>
	    <td>
	      <br>
	      <br>
	      <div id="sampleOpDiv" style="display : none;" align="center">
		<p align="left" class="board">This is the expected output for the above mentioned sample inputs</p>
	    	<a href="/">
                <button class="btn btn-medium btn-success">
                    Got It <i class="icon-thumbs-up icon-white"></i>
                </button>
            </a>
	      </div>
	    </td>
	  </tr>
	</table>
      </div>
      <br>
      <br>
    </td>
  </tr>
</table>
{% endblock %}

templates/codeit/feedback.html
{% extends "base.html" %}

{% block name %}Feedback{% endblock %}
{% block layout %}
<style type="text/css">
textarea{
  width: 60%;
  height:100px;
  background-color: #FFE4B5;
  color: #000000;
}
</style>
{% endblock %}
{% block content %}
<p class="lead text-info ">Please give your suggestions.</p>

<form action="." method="post">{% csrf_token %}
  <ul>
    <strong>
      <li>About Software<br>{{ fd.fdsoft }}</li>
      <li>About Problems<br>{{ fd.fdproblem }} </li>
      <li>Should we conduct such competitions later<br>{{ fd.fdsugg }}</li>
    </strong>
  </ul>
  <p class="lead"> {{ msg }} </p>
    {% if fd.errors %}
    {% for i in fd %}
    {% if i.errors %}
    {{ i.label }}
    {{ i.errors }}
    {% endif %}
    {% endfor %}
    {% endif %}
    <br>
  -->
  <button type="submit" class="btn btn-primary" data-title="Submit" title="Submit feedback" data-delay:{show:500,hide:100}>
    <i class="icon-user icon-white"></i> Submit
  </button>
</form>

{% endblock %}

templates/codeit/home.html
{% extends "base.html" %}

{% block name %} Home {% endblock %}

{% block content %}
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>

<table width="85%">
  <tr>
    <td><h2 title="See problems to solve">Problems<h2></td>
    <td align="right"><label>Logged in as <a href="#">{{ username }}</a> </label></td>
  </tr>
</table>

<hr>

<div class="row-fluid">
  <div class="row">
    <div class="span3" style="padding-left: 40px;">
      <img src="{{STATIC_URL}}img/110.jpg" width="60%" height="55%" class="image-rounded">
    </div>
    <div  style="padding-left: 5px;">
      <p style="font-size: 40px; color: #D2691E;"><b>Test your skills</b></p>
      <p style="font-size: 20px;"><br><br>Try to solve as many problems as you can within the stipulated time.<br>
        Click on a problem type to see problems.You will get complete marks for a <br> problem
        if the solution you submitted is agreed by judges.
        <p style="margin-left: 50px; font-size: 20px"><b>HAPPY CODING!!!</b></p>
      </p>
    </div>
    <div class="span3">
    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="container" style="padding-left: 30px;">
    <table width="85%" height="100%">
      <tr>
        <td align="center">
          <p id="easy" align="center" title="click to see easy problems below" onmouseover="changePointer(this)" style="background-color:#D3D3D3;" height="50" onmouseout="changePointer2(this)" onclick="changeColor(this)"><b>EASY</b></p>
        </td>
        <td align="center">
          <p id="medium" align="center" title="click to see medium problems below" onmouseover="changePointer(this)" style="background-color:#D3D3D3" onmouseout="changePointer2(this)"><b>MEDIUM</b></p>
        </td>
        <td align="center">
          <p id="hard" align="center" title="click to see hard problems below" onmouseover="changePointer(this)" style="background-color:#D3D3D3" onmouseout="changePointer2(this)"><b>HARD</b></p>
        </td>
      </tr>
    <tr>
  <td colspan="3">
  <div class="another">
  <b>
  <table id="myproblems" class="table table-hover" title="click to see details">
  </table>
  </b>
</div>
</td>
</tr>
</table>
</div>
</div>
<hr>
<script type="text/javascript" src="{{STATIC_URL}}js/home.js"></script>
{% endblock %}

templates/codeit/problem.html
{% extends "base.html" %}
{% block name %}Problem{% endblock %}

{% block layout %}
<style type="text/css">
.points{
  background-color: #7B68EE;
  color: #ffffff;
  width: 125px;
  padding: 4px;
  border: 1px solid;
  border-radius: 5px;
  margin-left: 78%;
}
.board{
    background-color:#FAFAD2;
    border:1px solid gray;
    border-radius: 5px;
    padding:10px;
    margin-left:20px;
    margin-right: 150px;
    color:#8B4513;
}
.bond{
  background-color: #009060;
  color: #ffffff;
  width: 150px;
  padding: 4px;
  border: 1px solid;
  border-radius: 5px;

}
.styled-select select {
   background: transparent;
   width: 148px;
   padding: 5px;
   line-height: 1;
   border: 0;
   border-radius: 0px;
   height: 27px;
   }
.styled-select {
   width: 120px;
   height: 27px;
   overflow: hidden;
   background: url("{{STATIC_URL}}img/down_arrow_select.jpg") no-repeat right #ddd;
   border: 1px solid #ccc;
 }
</style>
{% endblock %}

{% block content %}

<table width=85%>
  <tr>
    <td><h2>{{problem.name}}</h2></td>
    <td align="right"><label>Logged in as <a href="#">{{ username }}</a> </label></td>
  </tr>
</table>
<hr>
<div>
  <p class="points" align="center">
    <strong >Points :  &nbsp;{{ problem.points }}</strong>
  </p>
</div>

<p class="bond" align="center"><strong>Problem Statement</strong></p>


<div class="board" width="85%">
  {{ problem.statement|linebreaks }}
</div>


<br>
<p class="bond"><strong>Sample Input</strong></p><br>
<div class="board" width="85%">
  {{ problem.sample_input|linebreaks}}
</div>

<br>
<p class="bond"><strong>Sample Output</strong></p><br>
<div class="board" width="85%">
  {{ problem.sample_output|linebreaks}}
</div>

<br>

<form method="post" enctype="multipart/form-data" action="/solution/{{problem.id}}/" onsubmit="return validateForm()" >
  {% csrf_token %}
  <p class="bond"><strong>Upload code file</strong></p>
  <p>{{ fileuploadform.code }}&nbsp;&nbsp;
    <u><a title="Clear file path" href="#id_code" id="clear" style="cursor: pointer">Clear</a></p></u>
  <p class="bond"><strong>Select your language</strong></p>
  <div class="styled-select">
   <p>{{ fileuploadform.picked }}</p>
 </div>
 <br>
 <input type="submit" class="btn btn-primary xbt" value="Submit">
</form>
<script type="text/javascript" src="{{STATIC_URL}}js/problem.js"></script>

<div id="first" class="modal hide fade in" style="display: none; ">  
  <div class="modal-header"> 
    <div class="alert-error alert-block">
      <strong>Oh Snap!</strong> Change a few things up and try submitting again.
   </div> 
      <p style="color: black"><br>Uploaded file format does not match with selected</p>
    <div align="right">  
      <a href="#" class="btn btn-success" data-dismiss="modal">Got It!</a>  
      <a href="#" class="btn" data-dismiss="modal">Close</a>  
    </div>  
  </div>
</div>

<div id="second" class="modal hide fade in" style="display: none; ">  
  <div class="modal-header"> 
    <div class="alert-error alert-block">
      <strong>Oh Snap!</strong> Change a few things up and try submitting again.
   </div> 
      <p style="color: black"><br>Please select a file to upload</p>
    <div align="right">  
      <a href="#" class="btn btn-success" data-dismiss="modal">Got It!</a>  
      <a href="#" class="btn" data-dismiss="modal">Close</a>  
    </div>  
  </div>
</div>

{% endblock %}